"""qc_runner — one-command Pulse deploy + backtest on QuantConnect.

Unlocks Phase 2 (harsh-sim validation) and Phase 3 (walk-forward sweep)
by wrapping the QC API write methods into a high-level workflow.

Workflow:
    1. (optional) Create a QC project, OR re-use an existing one
    2. Push every file in `Pulse/` to the project
    3. Trigger a compile, poll until it succeeds
    4. Trigger a backtest with a chosen name + parameter overrides
    5. Poll until the backtest completes
    6. Return the final stats payload + backtest_id

Usage from CLI:
    python3 backtest_audit/qc_runner.py \\
        --project-id 31410009 \\
        --backtest-name "phase2-harsh-2025" \\
        --start-year 2025 --end-year 2025

Usage from Python:
    from backtest_audit.qc_runner import deploy_pulse, run_backtest
    pid = deploy_pulse(project_name="Pulse-2026")
    bt  = run_backtest(pid, "phase2-harsh-2025",
                       params={"start_year": "2025", "end_year": "2025"})
    print(bt["statistics"])

Notes:
  - Files are read from the local Pulse/ directory and pushed verbatim.
  - QC project's main.py MUST instantiate PulseAlgorithm; we ensure this by
    wrapping `Pulse/main.py` with a minimal entry stub if the project's
    main.py doesn't already import PulseAlgorithm.
  - Parameters are pushed via QC's project parameters JSON (left to caller
    to set in the project panel for now; future improvement: API for params).
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from typing import Optional

# Make repo root importable when invoked as a script
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from backtest_audit.qc_api import QCClient, QCError


# Files that constitute the Pulse package — pushed in order
# IMPORTANT: every Pulse/*.py that is imported by any other Pulse module or
# by main.py MUST be in this list, or QC compile will fail with
# "No module named X". Verified by test_qc_runner_manifest_complete.
PULSE_FILES = (
    "config.py",
    "universe.py",
    "slippage.py",
    "fees.py",
    "circuit.py",
    "features.py",
    "regime.py",
    "alt_data.py",
    "scalp_engine.py",
    "execution.py",
    "events.py",
    "trend_engine.py",
    "mr_engine.py",
    "portfolio.py",
    "sizing.py",
    "online_learning.py",   # imported by main.py
    "optimal_execution.py", # imported by main.py
    "runtime_overrides.py", # default empty; replaced per-backtest by sweep runner
    # ── APEX (Phase 1-6) ──────────────────────────────────────────────────
    "apex/__init__.py",
    "apex/config.py",
    "apex/registry.py",
    "apex/feature_vector.py",
    "apex/sizing.py",
    "apex/exits.py",
    "apex/apex_engine.py",
    "apex/integration.py",
    "apex/signals/__init__.py",
    "apex/signals/btc_onchain.py",
    "apex/signals/btc_dominance.py",
    "apex/signals/funding_native.py",
    "apex/signals/cross_asset.py",
    "apex/data/__init__.py",
    "apex/data/etf_flows.py",
    "apex/data/stablecoin_supply.py",
    "apex/data/token_unlocks.py",
    "apex/data/news_sentiment.py",
    "apex/data/onchain_valuation.py",
    "apex/ml/__init__.py",
    "apex/ml/dataset.py",
    "apex/ml/predict.py",
    "apex/ml/train.py",
    "main.py",              # entry point — keep last
)


# Static data CSVs bundled with the project. NOT Python — pushed via
# update_file as raw bytes. Loaders in main.py read them via ObjectStore
# or relative path. Optional: push only those that exist locally.
PULSE_DATA_FILES = (
    "apex_etf_flows.csv",
    "apex_token_unlocks.csv",
    "apex_stablecoin_supply.csv",
    "apex_news_sentiment.csv",
    "apex_model_v1.joblib",       # binary; only if it exists
)


# Minimal entry stub — QC requires a top-level main.py with the QCAlgorithm.
# It re-exports PulseAlgorithm under the conventional name LEAN looks for.
QC_TOP_LEVEL_MAIN_PY = '''# Auto-generated by backtest_audit.qc_runner — do not edit.
# Re-exports PulseAlgorithm so QC can find it as the top-level algorithm class.
from main import PulseAlgorithm  # noqa: F401
'''


def _read_pulse_dir(pulse_dir: str) -> dict[str, str]:
    """Load all PULSE_FILES from disk into a {filename: contents} dict.

    Files are pushed under the same basename to the QC project.
    The Pulse/__init__.py is intentionally NOT pushed — QC projects are
    flat directories, not packages.
    """
    out: dict[str, str] = {}
    for name in PULSE_FILES:
        path = os.path.join(pulse_dir, name)
        if not os.path.isfile(path):
            raise FileNotFoundError(f"Missing Pulse file: {path}")
        with open(path, encoding="utf-8") as f:
            content = f.read()
        # Rewrite imports: QC projects are flat — no Pulse package namespace.
        #   `from Pulse.X import Y`  → `from X import Y`
        #   `import Pulse.X as Z`    → `import X as Z`
        #   `from Pulse import X`    → `import X`             (NEW)
        #   `from Pulse import X, Y` → `import X; import Y`   (NEW)
        # The `from Pulse import X` form was missing; it shipped a runtime
        # error to QC ("No module named 'Pulse'") on diag-edge-discovery.
        content = content.replace("from Pulse.", "from ")
        content = content.replace("import Pulse.", "import ")
        # `from Pulse import alpha as a` → `import alpha as a`
        # `from Pulse import alpha, beta` → `import alpha\nimport beta`
        import re as _re
        def _rewrite_from_pulse_import(match: "_re.Match[str]") -> str:
            names = match.group(1)
            parts = [p.strip() for p in names.split(",") if p.strip()]
            return "\n".join(f"import {p}" for p in parts)
        content = _re.sub(
            r"^from Pulse import (.+)$",
            _rewrite_from_pulse_import,
            content,
            flags=_re.MULTILINE,
        )
        out[name] = content
    return out


def deploy_pulse(
    *,
    client: QCClient | None = None,
    project_id: int | None = None,
    project_name: str | None = None,
    pulse_dir: str | None = None,
    extra_top_level_main: bool = True,
) -> int:
    """Push all Pulse files to a QC project; create the project if needed.

    Args:
        client: optional pre-built QCClient (defaults to QCClient.from_env())
        project_id: existing project to update; if None, project_name must be set
        project_name: name for a new project (if project_id is None)
        pulse_dir: path to local Pulse/ directory (default: ../Pulse from this file)
        extra_top_level_main: if True, also write a tiny main.py at the QC project
            root that re-exports PulseAlgorithm

    Returns:
        The project_id (existing or newly created).
    """
    c = client or QCClient.from_env()
    pulse_dir = pulse_dir or os.path.join(_ROOT, "Pulse")

    if project_id is None:
        if not project_name:
            raise ValueError("Either project_id or project_name is required")
        r = c.create_project(name=project_name, language="Py")
        project_id = int(r["projects"][0]["projectId"])
        print(f"[qc_runner] Created project {project_name!r} pid={project_id}")
    else:
        print(f"[qc_runner] Updating existing project pid={project_id}")

    files = _read_pulse_dir(pulse_dir)
    if extra_top_level_main:
        # Some QC project templates already include a top-level main.py;
        # we overwrite it with the re-export shim that points at our Pulse main.
        # The Pulse/main.py we just pushed becomes accessible as `from main import ...`.
        # That circular-looking thing works because QC projects are flat.
        # Note: many users will already have main.py in their project; this
        # ensures it's the right one.
        # We do NOT push this when files already include main.py at root —
        # users may want to keep their own custom main.
        pass   # The Pulse/main.py we pushed already IS the top-level main.py.

    print(f"[qc_runner] Pushing {len(files)} files...")
    for name in files:
        try:
            c.update_file(project_id, name, files[name])
            print(f"  ✓ {name} ({len(files[name]):,} chars)")
        except QCError as exc:
            print(f"  ✗ {name}: {exc}")
            raise

    # Push optional static data CSVs (Apex)
    pushed_data = 0
    for fname in PULSE_DATA_FILES:
        path = os.path.join(pulse_dir, fname)
        if not os.path.isfile(path):
            continue
        try:
            with open(path, "rb") as f:
                content_bytes = f.read()
            # update_file expects str — decode best-effort for CSVs;
            # joblib is binary so we skip it for now (would need
            # ObjectStore upload via separate API).
            try:
                content = content_bytes.decode("utf-8")
            except UnicodeDecodeError:
                print(f"  ⚠ {fname} is binary, skipping (push manually via QC IDE)")
                continue
            c.update_file(project_id, fname, content)
            pushed_data += 1
            print(f"  ✓ {fname} ({len(content):,} chars)")
        except QCError as exc:
            print(f"  ✗ {fname}: {exc}")
    if pushed_data:
        print(f"[qc_runner] Pushed {pushed_data} data CSV(s)")
    print(f"[qc_runner] All files pushed to pid={project_id}")
    return project_id


def run_backtest(
    project_id: int,
    backtest_name: str,
    *,
    client: QCClient | None = None,
    compile_timeout_s: int = 180,
    backtest_timeout_s: int = 1800,
) -> dict:
    """Compile + run a backtest; poll until completion.

    Returns the final backtest payload (with .statistics, .totalPerformance, etc.).
    """
    c = client or QCClient.from_env()

    print(f"[qc_runner] Submitting compile for pid={project_id}...")
    cr = c.create_compile(project_id)
    compile_id = cr.get("compileId") or cr.get("CompileId")
    if not compile_id:
        raise QCError(f"compile_id missing from response: {cr}")
    print(f"[qc_runner] compile_id={compile_id}; polling up to {compile_timeout_s}s")
    final_compile = c.wait_for_compile(
        project_id, compile_id, timeout_s=compile_timeout_s, poll_s=3,
    )
    state = final_compile.get("state") or final_compile.get("State")
    if state != "BuildSuccess":
        errors = final_compile.get("errors") or final_compile.get("logs") or []
        raise QCError(f"compile failed (state={state}): {errors}")
    print(f"[qc_runner] ✓ compile succeeded")

    print(f"[qc_runner] Submitting backtest {backtest_name!r}...")
    br = c.create_backtest(project_id, compile_id, backtest_name)
    bid = (br.get("backtest", {}) or {}).get("backtestId") or br.get("backtestId")
    if not bid:
        raise QCError(f"backtest_id missing from response: {br}")
    print(f"[qc_runner] backtest_id={bid}; polling up to {backtest_timeout_s}s")

    final_bt = c.wait_for_backtest(
        project_id, bid, timeout_s=backtest_timeout_s, poll_s=15,
    )
    print(f"[qc_runner] ✓ backtest completed")
    return final_bt


def deploy_and_run(
    *,
    project_id: int | None = None,
    project_name: str | None = None,
    backtest_name: str = "pulse-backtest",
    client: QCClient | None = None,
) -> tuple[int, dict]:
    """Convenience: deploy_pulse + run_backtest in one shot.

    Returns (project_id, backtest_payload).
    """
    c = client or QCClient.from_env()
    pid = deploy_pulse(client=c, project_id=project_id, project_name=project_name)
    bt  = run_backtest(pid, backtest_name, client=c)
    return pid, bt


# ─── CLI ─────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--project-id", type=int,
                    help="Existing QC project ID to push to + run")
    ap.add_argument("--project-name",
                    help="If --project-id is omitted, create a new project with this name")
    ap.add_argument("--backtest-name", default="pulse-backtest",
                    help="Name for the new backtest")
    ap.add_argument("--no-run", action="store_true",
                    help="Push files only; don't compile or run")
    args = ap.parse_args()

    client = QCClient.from_env()
    pid = deploy_pulse(
        client=client,
        project_id=args.project_id,
        project_name=args.project_name,
    )

    if args.no_run:
        print(f"[qc_runner] Done (no-run). project_id={pid}")
        return

    bt = run_backtest(pid, args.backtest_name, client=client)
    print(f"\n=== BACKTEST RESULT ===")
    print(f"name: {bt.get('name')}")
    stats = bt.get("statistics") or {}
    for k, v in list(stats.items())[:20]:
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
