"""qc_sweep_runner — fully-automated Phase 3 walk-forward sweep on QC.

PLAN.md §5 — runs each (param_set, window) combination as a QC backtest,
collects results, and feeds them into regime_runner.sweep() for survivability
scoring.

Workflow per (param_id, params, window):
    1. Push runtime_overrides.py with the params dict to the QC project
    2. Push start_year / end_year QC parameters (via re-pushing main.py
       with hard-coded dates — see _embed_window_dates)
    3. Trigger compile + backtest via qc_runner.run_backtest
    4. Pull final stats; convert to WindowResult
    5. Optionally pull orders for finer-grained gap analysis

Run-mode flags:
    - dry_run=True   — skip QC calls; emit synthetic WindowResult with
                       random returns. Use for smoke testing.
    - parallel=False — sequential (default; QC backtests are serialized
                       per-account). Future: parallelize across multiple
                       projects.

Output: SweepResult identical to regime_runner.sweep() output.
HTML report writeable via report.render_sweep().

Notes on cloud time:
    - Default 50 param sets × 6 windows = 300 backtests
    - Typical 1-year crypto backtest: 5-15 minutes cloud time
    - Total: 25-75 cloud-hours per full sweep
    - Mitigations: dry_run=True for code paths; --max-windows to subset;
      --max-params to cap the sweep size
"""

from __future__ import annotations

import argparse
import os
import random
import sys
import time
from dataclasses import dataclass
from typing import Callable, Sequence

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from backtest_audit.qc_api import QCClient, QCError
from backtest_audit.qc_runner import deploy_pulse, run_backtest
from backtest_audit.regime_runner import (
    RegimeWindow, REGIME_WINDOWS,
    WindowResult, SweepResult, sweep, score_param_set,
)
from backtest_audit.param_sweep import pulse_param_sweep


# ─── Runtime overrides file pusher ──────────────────────────────────────────

def render_runtime_overrides(params: dict) -> str:
    """Render the params dict as a runtime_overrides.py file for QC."""
    lines = [
        "# Auto-generated by backtest_audit.qc_sweep_runner — do not edit.",
        "# Pulse._apply_runtime_overrides() reads this and merges OVERRIDES",
        "# into the config module before the algorithm initializes.",
        "",
        "OVERRIDES = {",
    ]
    for k, v in sorted(params.items()):
        if isinstance(v, str):
            lines.append(f'    {k!r}: {v!r},')
        else:
            lines.append(f'    {k!r}: {v!r},')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# Map param_sweep parameter names → Pulse.config constant names
PARAM_TO_CONFIG: dict[str, str] = {
    "entry_threshold":           "SCALP_ENTRY_THRESHOLD",
    "high_conviction_threshold": "SCALP_HIGH_CONVICTION_THRES",
    "quick_take_profit":         "QUICK_TAKE_PROFIT_PCT",
    "tight_stop_loss":           "TIGHT_STOP_LOSS_PCT",
    "atr_tp_mult":               "ATR_TP_MULT",
    "atr_sl_mult":               "ATR_SL_MULT",
    "trail_activation":          "TRAIL_ACTIVATION_PCT",
    "trail_stop_pct":            "TRAIL_STOP_PCT",
    "time_stop_hours":           "TIME_STOP_HOURS",
    "max_positions":             "MAX_POSITIONS",
    "max_position_usd":          "TARGET_CAPACITY_USD",   # placeholder
    "target_position_ann_vol":   "TARGET_POSITION_ANN_VOL",
}


def remap_params_to_config_names(params: dict) -> dict:
    """Translate human-friendly sweep param names → Pulse.config constant names.

    Unknown keys are passed through verbatim.
    """
    out = {}
    for k, v in params.items():
        out[PARAM_TO_CONFIG.get(k, k)] = v
    return out


def push_runtime_overrides(client: QCClient, project_id: int,
                           params: dict) -> None:
    """Upload runtime_overrides.py with the given params to the QC project."""
    contents = render_runtime_overrides(remap_params_to_config_names(params))
    client.update_file(project_id, "runtime_overrides.py", contents)


# ─── QC stats → WindowResult ────────────────────────────────────────────────

def _safe_float(s, default: float = 0.0) -> float:
    if s is None:
        return default
    try:
        return float(str(s).replace("%", "").replace(",", ""))
    except (ValueError, TypeError):
        return default


def stats_to_window_result(window_name: str, stats: dict,
                           total_orders_hint: int | None = None) -> WindowResult:
    """Translate QC backtest statistics dict into a WindowResult."""
    net_ret = _safe_float(stats.get("Net Profit"))
    drawdown = _safe_float(stats.get("Drawdown"))
    sharpe   = _safe_float(stats.get("Sharpe Ratio"))
    win_rate = _safe_float(stats.get("Win Rate"))
    trades   = int(_safe_float(stats.get("Total Orders"),
                                default=total_orders_hint or 0))
    return WindowResult(
        window=window_name,
        net_return_pct=net_ret,
        drawdown_pct=abs(drawdown),
        sharpe=sharpe,
        win_rate_pct=win_rate,
        trades=trades,
    )


# ─── Window date embedding ──────────────────────────────────────────────────

def render_window_overrides(window: RegimeWindow,
                            extra_overrides: dict | None = None) -> str:
    """Render a runtime_overrides.py that hard-codes window dates.

    Pulse.main.py reads start_year/end_year via QC parameters by default,
    but for sweeps it's simpler to bake the dates into the overrides file
    so we don't need to mutate QC's parameter panel for each combination.

    We use the override keys 'PULSE_OVERRIDE_START' and 'PULSE_OVERRIDE_END'
    which Pulse.main.py recognizes (see _apply_runtime_overrides documentation).
    """
    overrides = dict(extra_overrides or {})
    overrides["PULSE_OVERRIDE_START_YEAR"] = window.start.year
    overrides["PULSE_OVERRIDE_START_MONTH"] = window.start.month
    overrides["PULSE_OVERRIDE_START_DAY"]   = window.start.day
    overrides["PULSE_OVERRIDE_END_YEAR"]    = window.end.year
    overrides["PULSE_OVERRIDE_END_MONTH"]   = window.end.month
    overrides["PULSE_OVERRIDE_END_DAY"]     = window.end.day
    return render_runtime_overrides(overrides)


# ─── Sweep core ─────────────────────────────────────────────────────────────

def make_qc_backtest_fn(
    client: QCClient,
    project_id: int,
    *,
    backtest_name_prefix: str = "sweep",
    push_pulse_first: bool = False,
    use_harsh_sim: bool = False,
) -> Callable[[RegimeWindow, dict], WindowResult]:
    """Build a backtest_fn closure suitable for regime_runner.sweep().

    Returns a callable (window, params) → WindowResult that:
      1. Pushes runtime_overrides.py with the merged params + window dates
      2. Triggers compile + backtest in QC
      3. Polls until completion
      4. Translates stats into a WindowResult

    Args:
        push_pulse_first: if True, deploy_pulse() once before the first call
        use_harsh_sim: if True, also push 'use_harsh_sim': True into overrides
                       (so the QC parameter panel doesn't need to be edited)
    """
    deploy_done = {"flag": not push_pulse_first}   # bool wrapped in mutable

    def _bt_fn(window: RegimeWindow, params: dict) -> WindowResult:
        if not deploy_done["flag"]:
            deploy_pulse(client=client, project_id=project_id)
            deploy_done["flag"] = True

        merged = dict(params)
        if use_harsh_sim:
            merged["use_harsh_sim"] = True
        # Push the per-(param,window) runtime overrides file
        contents = render_window_overrides(window, merged)
        client.update_file(project_id, "runtime_overrides.py", contents)

        bt_name = f"{backtest_name_prefix}_{window.name}_{int(time.time())}"
        bt = run_backtest(project_id, bt_name, client=client)
        stats = bt.get("statistics") or {}
        return stats_to_window_result(window.name, stats)

    return _bt_fn


def run_sweep(
    client: QCClient,
    project_id: int,
    *,
    n_samples: int = 50,
    windows: Sequence[RegimeWindow] = REGIME_WINDOWS,
    backtest_name_prefix: str = "sweep",
    use_harsh_sim: bool = False,
    push_pulse_first: bool = True,
    seed: int = 42,
) -> SweepResult:
    """High-level: generate Latin-hypercube sweep and run on QC.

    n_samples × len(windows) backtests run in sequence.
    Returns a SweepResult ranked by survivability score.
    """
    param_sets = pulse_param_sweep(n_samples=n_samples, seed=seed)
    bt_fn = make_qc_backtest_fn(
        client, project_id,
        backtest_name_prefix=backtest_name_prefix,
        push_pulse_first=push_pulse_first,
        use_harsh_sim=use_harsh_sim,
    )
    return sweep(param_sets, bt_fn, windows=windows)


# ─── Dry-run mode ───────────────────────────────────────────────────────────

def _dry_run_backtest_fn(seed: int = 42):
    """Deterministic synthetic backtest_fn — no QC calls.

    For each (window, params) emits a WindowResult with returns drawn from
    a normal distribution scaled by a function of the params. Useful for
    smoke-testing the sweep harness without burning QC cloud time.
    """
    rng = random.Random(seed)

    def _fn(window: RegimeWindow, params: dict) -> WindowResult:
        # Fake "edge": more aggressive entries → higher mean but higher std
        et = float(params.get("entry_threshold", 0.55))
        edge = (0.65 - et) * 100   # lower threshold → more edge (synthetic)
        ret = rng.gauss(edge, 15.0)
        dd  = abs(rng.gauss(8.0, 5.0))
        return WindowResult(
            window=window.name,
            net_return_pct=ret,
            drawdown_pct=dd,
            sharpe=ret / max(dd, 1.0),
            win_rate_pct=50.0 + rng.gauss(0, 5),
            trades=int(rng.gauss(500, 100)),
        )

    return _fn


def run_sweep_dry(
    n_samples: int = 50,
    windows: Sequence[RegimeWindow] = REGIME_WINDOWS,
    seed: int = 42,
) -> SweepResult:
    """Dry-run: synthetic backtest_fn, no QC calls. Smoke test only."""
    param_sets = pulse_param_sweep(n_samples=n_samples, seed=seed)
    return sweep(param_sets, _dry_run_backtest_fn(seed=seed), windows=windows)


# ─── CLI ─────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--project-id", type=int,
                    help="QC project to push Pulse + run sweep into")
    ap.add_argument("--n-samples", type=int, default=50,
                    help="Number of Latin-hypercube parameter sets (default 50)")
    ap.add_argument("--use-harsh-sim", action="store_true",
                    help="Run all sweep backtests under harsh simulator overrides")
    ap.add_argument("--max-windows", type=int,
                    help="Limit to first N windows (for cost-bounded runs)")
    ap.add_argument("--dry-run", action="store_true",
                    help="Skip QC calls; emit synthetic results")
    ap.add_argument("--out", default="backtest_audit/reports/phase3_sweep.html",
                    help="HTML output path")
    args = ap.parse_args()

    windows = REGIME_WINDOWS
    if args.max_windows:
        windows = REGIME_WINDOWS[:args.max_windows]

    if args.dry_run:
        print(f"[dry-run] n_samples={args.n_samples} windows={len(windows)}")
        result = run_sweep_dry(n_samples=args.n_samples, windows=windows)
    else:
        if not args.project_id:
            ap.error("--project-id required unless --dry-run")
        client = QCClient.from_env()
        result = run_sweep(
            client, args.project_id,
            n_samples=args.n_samples, windows=windows,
            use_harsh_sim=args.use_harsh_sim,
        )

    print()
    print(result.summary_text())

    # Render HTML
    from backtest_audit.report import write_audit_page
    out_path = write_audit_page(
        args.out,
        title=f"Phase 3 Sweep ({args.n_samples} param sets × {len(windows)} windows)",
        sweep_result=result,
    )
    print(f"\n✓ Wrote: {out_path}")


if __name__ == "__main__":
    main()
